settings:
  jms:
    hostname: localhost
    port: 61613
    user:
    password:
    results_queue: /queue/wg.results
    candidate_words_queue: /queue/wg.candidate.words
    processed_words_queue: /queue/wg.processed.words
  wg:
    splitter_options: ",,"
    splitter_key_value: "_"
  wordlist:
    characters: "abcd"
    min_length: 2
    max_length: 4
    max_char_occurs: "ab_5"
    min_char_occurs: "b_1,,a_1"
    min_char_list_occurs: "ab_1,,c_0"
    max_char_list_occurs: "ab_5"
    max_run_iterations: 10000
    prefix_string:
    postfix_string:
    max_consecutive_chars: 2
    include_regex:
    exclude_regex:
    